### ISSUE TITLE
Compile error: Type mismatch: cannot convert from Stream<Object> to Stream<LongSummaryStatistics>

### ISSUE THREAD

**Issue by loganathan001** [JosePaumard/streams-utils#1]
I get this compilation error with shiftingWindowSummarizingLong(LongStream longStream, int rollingFactor) method int the StreamsUtils (Line:595). How can I fix this.

![compile error](https://cloud.githubusercontent.com/assets/3040698/19147977/503ad22e-8bd8-11e6-997d-4dbd4a8b3db0.png)

**Comment by JosePaumard** [comment]
Thank you for the report. This issue is not seen in other IDE / compilers, I will check if it is an Eclipse issue or not. One way to fix it could be to tell the compiler the static type by adding <LongSummaryStatistics> before the .stream() call.

**Comment by loganathan001** [comment]
Type casting fixes the issue and tests are passed. But is that the correct way? Or am I missing something?
return (Stream<LongSummaryStatistics>)StreamSupport.stream(ofLongSpliterator, false).map(
                str -> str.collect(
                        LongSummaryStatistics::new,
                        LongSummaryStatistics::accept,
                        LongSummaryStatistics::combine
                )
        );

**Comment by JosePaumard** [comment]
Indeed this compile error is seen in Eclipse and not in IntelliJ. The standard command line javac compiler does not raise any error neither. It seems to me to be an Eclipse compiler bug, but I cannot be sure. 

The workaround consists in expanding the second method reference: 
from : LongSummaryStatistics::accept
to : (longSummaryStatistics, value) -> longSummaryStatistics.accept(value)

This workaround is active in version 1.1.1.
