### ISSUE TITLE
I found an interesting issue in GroupingSpliteratorTest

### ISSUE THREAD

**Issue by americanstone** [JosePaumard/streams-utils#18]
this test in java8 the count is 4L but java11 is 3L. don't know why
    
        @Test
        public void should_correctly_count_the_elements_of_a_sized_stream() {
        // Given
        Stream<String> strings = Stream.of("o", "1", "2", "3", "4", "5", "6", "7", "8", "9", "c");
        int groupingFactor = 3;

        Stream<Stream<String>> stream = StreamsUtils.group(strings, groupingFactor);

        // When
        long count = stream.count();

        // Then
        assertThat(count).isEqualTo(3L);
    }

        /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -ea - 
        Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ 
        IDEA.app/Contents/lib/idea_rt.jar=58943:/Applications/IntelliJ IDEA.app/Contents/bin" - 
        Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ 
        IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ
        org.junit.ComparisonFailure: 
        Expected :3L
        Actual   :4L
        <Click to see difference>

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.dealer.streamsUtils.spliterators.GroupingSpliteratorTest.should_correctly_count_the_elements_of_a_sized_stream(GroupingSpliteratorTest.java:142)
	....

        ===============================================
        Default Suite
        Total tests run: 1, Failures: 1, Skips: 0
        ===============================================

**Comment by americanstone** [comment]
the real question is why the test expected grouping 11 elements with groupingFactor 3 get 3 grouped stream instead of 4.

**Comment by JosePaumard** [comment]
The result is 3 because this operator gives you only substream of size groupingSize. In this stream, there is one missing element to create the 4th substream, thus the result. 
There was a change in way the size of SIZED streams are computed in 9. And this new way was not properly supported in Streams Utils, thus the rather large patch between 8 and 9. I fact the test you are looking at is not present in Stream Utils 1.7 and was added to 2.0 because it failed due to this change.

**Comment by americanstone** [comment]
thank you for explaining to me
