### ISSUE TITLE
Cycle for parallel stream create unlimited threads

### ISSUE THREAD

**Issue by uitnetwork** [JosePaumard/streams-utils#4]
Cycle may not be work with parallel stream. Here is an example:

`Stream<String> names = Stream.of("Test 1", "Test 2", "Test 3", "Test 4").parallel();
        cycle(names).forEach(System.out::println);`

I think input `false` (instead of `stream.isParallel()` into `StreamSupport.stream()` inside `StreamsUtils.cycle()` can make it work (but it's no parallel anymore)

**Comment by JosePaumard** [comment]
The real question is: what do you expect as a result? Cycling in parallel does not make sense imho. There are other cases like that in Streams Utils.

**Comment by uitnetwork** [comment]
Yeah. I agree that cycling in parallel does not make sense. I'm a little surprise when I saw the code and thought that it might support parallel. Then I looked into the code to see how it works. But it does not work so I just reported it just in case someone mistakenly use the API with parallel stream.

**Comment by JosePaumard** [comment]
What do you think would be a good behavior? Throw an UnsupportedOperationException to tell the caller that parallel stream is not supported? Or silently conduct the computation in a non-paralle stream?

**Comment by uitnetwork** [comment]
In my opinion, conducting the computation in a non-parallel stream and put it into Java doc is good.

**Comment by JosePaumard** [comment]
Ok, thank you for your input!

**Comment by uitnetwork** [comment]
You are welcome.

**Comment by r0main** [comment]
If you change the behavior of the stream given by the caller you should inform him. Maybe not an exception. But at least a log warn. Otherwise one day he'll discover by surprise a performance issue...
