### ISSUE TITLE
Rolling fails on stream built from SortedMap

### ISSUE THREAD

**Issue by jpmilhau** [JosePaumard/streams-utils#7]
Your api is really interesting but I have an issue:

The following code fails:

`SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");`
`SortedMap<Date, Long> sortedMap = new TreeMap<Date, Long>();`
`try {`
`   sortedMap.put(formatter.parse("01/05/2017"), 1L);`
`   sortedMap.put(formatter.parse("02/05/2017"), 2L);`
`   sortedMap.put(formatter.parse("03/05/2017"), 3L);`
`   sortedMap.put(formatter.parse("04/05/2017"), 2L);`
`   sortedMap.put(formatter.parse("05/05/2017"), 3L);`
`} catch (ParseException e) {`
`   e.printStackTrace();`
`}`
`StreamsUtils.roll(sortedMap.entrySet().stream(), 2);`

with:

Exception in thread "main" java.lang.IllegalStateException
    		at java.util.Spliterator.getComparator(Unknown Source)
    		at java.util.stream.StreamOpFlag.fromCharacteristics(Unknown Source)
    		at java.util.stream.StreamSupport.stream(Unknown Source)
    		at org.paumard.streams.StreamsUtils.roll(StreamsUtils.java:287)
    		at com.streamutils.test.StreamUtilsTest.main(StreamUtilsTest.java:174)

whereas the following code is successful:

`SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");`
`LinkedHashMap<Date, Long> linkedHashMap = new LinkedHashMap<Date, Long>();`
`try {`
`   linkedHashMap.put(formatter.parse("01/05/2017"), 1L);`
`   linkedHashMap.put(formatter.parse("02/05/2017"), 2L);`
`   linkedHashMap.put(formatter.parse("03/05/2017"), 3L);`
`   linkedHashMap.put(formatter.parse("04/05/2017"), 2L);`
`   linkedHashMap.put(formatter.parse("05/05/2017"), 3L);`
`} catch (ParseException e) {`
`   e.printStackTrace();`
`}`
`StreamsUtils.roll(linkedHashMap.entrySet().stream(), 2);`

Any reason for that?

**Comment by JosePaumard** [comment]
First of all, thank you for your bug report!

It comes from the fact that the stream is ordered, and the rolled stream is also ordered, which does not make any sense. I suspect it affects other streams as wel... Expect a fix very soon. 

-- José

**Comment by JosePaumard** [comment]
I just pushed a fix for the Roll operator, and for others too in 1.6. I discovered that the sorted stream were not properly handle by StreamsUtils, now it is the case.

**Comment by jpmilhau** [comment]
Thanks for the fix.
